name: batch-submitter lint and unit tests

on:
  push:
    paths:
      - 'batch-submitter/**'
    branches:
      - 'main'
      - '*'
  pull_request:
    paths:
      - 'batch-submitter/*'

defaults:
  run:
    working-directory: './batch-submitter'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint
        run: make lint

      - name: Unit Test
        run: make test
