name: batch-submitter lint and unit tests

on:
  push:
    paths:
      - 'batch-submitter/**'
    branches:
      - 'main'
      - '*'
  pull_request:
    paths:
      - 'batch-submitter/*'

defaults:
  run:
    working-directory: './batch-submitter'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: batch-submitter

  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Test
        run: make test
