name: gas-oracle lint and unit tests

on:
  push:
    paths:
      - 'gas-oracle/**'
  pull_request:
    paths:
      - 'gas-oracle/*'

defaults:
  run:
    working-directory: './gas-oracle'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17

      - uses: actions/checkout@v3

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          working-directory: gas-oracle

  unittest:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Test
        run: go test -v ./...
